name: Build MPV (d4rk0, Windows x64)

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 3 * * 1"   # opcional: lunes 03:00 UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    env:
      MSYSTEM: CLANG64
      CHERE_INVOKING: 1
      PACKAGE_ID: d4rk0.mpv

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1) Resolver la ÚLTIMA release estable de MPV (robusto)
      - name: Resolve latest stable MPV release
        id: mpvver
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}       # necesario para gh
          GITHUB_TOKEN: ${{ github.token }}   # para la API REST
        run: |
          $ErrorActionPreference = "Stop"

          # 1) Intento con gh (y verificación del exit code)
          $tag = ""
          if (Get-Command gh -ErrorAction SilentlyContinue) {
            if (-not $env:GH_TOKEN) { $env:GH_TOKEN = $env:GITHUB_TOKEN }
            $tag = $(gh release view --repo mpv-player/mpv --json tagName --jq '.tagName' 2>$null)
            if ($LASTEXITCODE -ne 0) { $tag = "" }
          }

          # 2) Fallback por REST si hace falta
          if (-not $tag) {
            $headers = @{
              "User-Agent"            = "d4rk0-ci"
              "Accept"                = "application/vnd.github+json"
              "X-GitHub-Api-Version"  = "2022-11-28"
              "Authorization"         = "Bearer $env:GITHUB_TOKEN"
            }
            $resp = Invoke-RestMethod -Method GET -Uri "https://api.github.com/repos/mpv-player/mpv/releases/latest" -Headers $headers
            $tag = $resp.tag_name
          }

          if (-not $tag) { throw "No pude resolver el tag de MPV." }
          $ver = $tag.TrimStart('v')

          "MPV_TAG=$tag" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          "MPV_VER=$ver" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          Write-Host "MPV tag: $tag / version: $ver"

      # 2) MSYS2 (CLANG64) + toolchain + dependencias
      - name: Setup MSYS2 (CLANG64) + packages
        uses: msys2/setup-msys2@v2
        with:
          msystem: clang64
          update: true
          install: >-
            git
            zip
            curl
            jq
            mingw-w64-clang-x86_64-toolchain
            mingw-w64-clang-x86_64-python
            mingw-w64-clang-x86_64-meson
            mingw-w64-clang-x86_64-ninja
            mingw-w64-clang-x86_64-pkgconf
            mingw-w64-clang-x86_64-ffmpeg
            mingw-w64-clang-x86_64-libass
            mingw-w64-clang-x86_64-libplacebo
            mingw-w64-clang-x86_64-harfbuzz
            mingw-w64-clang-x86_64-uchardet
            mingw-w64-clang-x86_64-vulkan-headers
            mingw-w64-clang-x86_64-vulkan-loader
            mingw-w64-clang-x86_64-spirv-cross
            mingw-w64-clang-x86_64-shaderc
            mingw-w64-clang-x86_64-ntldd
            # ADDED: extras para paridad/plus con shinchiro
            mingw-w64-clang-x86_64-luajit
            mingw-w64-clang-x86_64-mujs
            mingw-w64-clang-x86_64-zimg
            mingw-w64-clang-x86_64-lcms2
            mingw-w64-clang-x86_64-libarchive
            mingw-w64-clang-x86_64-libbluray
            mingw-w64-clang-x86_64-libdvdread
            mingw-w64-clang-x86_64-libdvdnav

      # 3) Descargar el código fuente de MPV (tarball del tag estable)
      - name: Fetch mpv source
        shell: msys2 {0}
        run: |
          set -euxo pipefail
          curl -fsSL -o mpv.tar.gz "https://github.com/mpv-player/mpv/archive/refs/tags/${MPV_TAG}.tar.gz"
          tar -xzf mpv.tar.gz
          mv "mpv-${MPV_VER}" mpv-src

      # 4) Parche seguro por si FFmpeg>=8 (no falla si no aplica)
      - name: Patch FF_PROFILE -> AV_PROFILE (safe)
        shell: msys2 {0}
        working-directory: mpv-src
        run: |
          set -e
          sed -i 's/FF_PROFILE_/AV_PROFILE_/g' demux/demux_mkv.c || true

      # 5) Configurar + Compilar con Meson/Ninja
      - name: Configure & Build (Meson/Ninja)
        shell: msys2 {0}
        working-directory: mpv-src
        run: |
          set -euxo pipefail
          meson setup build --buildtype=release
          meson compile -C build -v

      # 6) Empaquetar portable: mpv.exe + DLLs + scripts/OSC (robusto)
      - name: Make portable ZIP
        shell: msys2 {0}
        working-directory: mpv-src
        run: |
          set -euo pipefail
          out="../dist"
          mkdir -p "$out"

          # Ejecutables
          cp -v build/mpv.exe "$out/" || (echo "mpv.exe no encontrado" && exit 1)
          [ -f build/mpv.com ] && cp -v build/mpv.com "$out/"

          echo "Resolviendo DLLs con ntldd..."
          prefix_unix="/clang64/bin"

          # 1) Extraer posibles DLLs (tolerar lista vacía)
          mapfile -t DLLS < <(
            ntldd -R build/mpv.exe \
              | sed -n 's/.*=>[[:space:]]*\(.*\.dll\).*/\1/p' \
              | tr -d '\r'
          ) || true

          # 2) Normalizar y copiar sólo las de /clang64/bin
          for p in "${DLLS[@]}"; do
            p_u="$(cygpath -u "$p" 2>/dev/null || echo "$p")"
            if [[ "$p_u" == $prefix_unix/*.dll ]]; then
              echo "  + $p_u"
              cp -nv "$p_u" "$out/" || true
            fi
          done

          # ADDED: scripts oficiales y config portable (OSC/UI)
          mkdir -p "$out/portable_config/scripts"
          cp -v "player/lua/osc.lua"         "$out/portable_config/scripts/osc.lua"
          cp -v "player/lua/stats.lua"       "$out/portable_config/scripts/stats.lua"
          cp -v "player/lua/ytdl_hook.lua"   "$out/portable_config/scripts/ytdl_hook.lua"
          cp -v "TOOLS/lua/autoload.lua"     "$out/portable_config/scripts/autoload.lua"

          cat > "$out/portable_config/mpv.conf" << 'EOF'
          osc=yes
          input-default-bindings=yes
          force-window=yes
          ytdl=yes
          EOF

          cd "$out"
          /usr/bin/zip -9 -r "d4rk0.mpv-${MPV_VER}-windows-x64.zip" .

      # 7) Localizar el ZIP con ruta absoluta de Windows (para las actions)
      - name: Locate ZIP (Windows absolute path)
        id: locatezip
        shell: pwsh
        run: |
          $name = "d4rk0.mpv-$env:MPV_VER-windows-x64.zip"
          $zip = Get-ChildItem -Path "$env:GITHUB_WORKSPACE" -Recurse -File -Filter $name | Select-Object -First 1
          if (-not $zip) { throw "ZIP not found: $name" }
          "ZIP_PATH_WIN=$($zip.FullName)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          Write-Host "ZIP found at: $($zip.FullName)"

      # 8) Subir artefacto (usa la ruta absoluta)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: d4rk0.mpv-${{ env.MPV_VER }}-windows-x64
          path: ${{ env.ZIP_PATH_WIN }}
          if-no-files-found: error

      # 9) Publicar en GitHub Releases (crea/actualiza release mpv-<versión>)
      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: mpv-${{ env.MPV_VER }}
          name: "MPV ${{ env.MPV_VER }} (d4rk0 build, Windows x64)"
          files: ${{ env.ZIP_PATH_WIN }}
          make_latest: true
          fail_on_unmatched_files: true
